version: '3'
volumes:
  cache:
    driver: local
  db-data:
    driver: local
  minio-data:
    driver: local

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    stdin_open: true
    depends_on:
      - backend
    ports:
      - '80:3000'

  backend:
    build:
      context: .
    container_name: tasklist
    depends_on:
      - db
      - redis
      - minio
    env_file:
      - .env.example
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasklist?currentSchema=tasklist
      SPRING_DATA_REDIS_HOST: redis
    ports:
      - '8081:8080'

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 537915
      POSTGRES_DB: tasklist
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ZXJ0ZWRydHlldGVh
    volumes:
      - cache:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio
