spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: 537915
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: YXNkZmdoamtkYXNkZ2ZoZmRoZGZnc2RmZ2Rm
    access: 36000000
    refresh: 2592000000
