spring:
  config:
    # import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: ZXJ0ZWRydHlldGVh
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: 537915
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
security:
  jwt:
    secret: YXNkZmdoamtkYXNkZ2ZoZmRoZGZnc2RmZ2Rm
    access: 1
    refresh: 30
springdoc:
  override-with-generic-response: false #убирает сообщения об ошибках в сваггере