spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: 537915
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
#      data-locations: classpath:db-init/initdb.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
security:
  jwt:
    secret: YXNkZmdoamtkYXNkZ2ZoZmRoZGZnc2RmZ2Rm
    access: 36000000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false #убирает сообщения об ошибках в сваггере