create table if not exists users
(
    id       bigint generated by default as identity primary key,
    NAME     VARCHAR(255) NOT NULL,
    username varchar(255) not null unique,
    password varchar(255) not null
);

create table if not exists tasks
(
    id              bigint generated by default as identity primary key,
    title           varchar(255) not null,
    description     varchar(255) null,
    status          varchar(255) not null,
    expiration_date timestamp    null
);

create table if not exists users_tasks
(
    user_id bigint not null,
    task_id bigint not null,
    primary key (user_id, task_id),
    constraint fk_users_task_users foreign key (user_id) references users (id) on delete cascade on update no action,
    constraint fk_users_task_tasks foreign key (task_id) references tasks (id) on delete cascade on update no action
);

create table if not exists users_roles
(
    user_id bigint       not null,
    role    varchar(255) not null,
    primary key (user_id, role),
    constraint fk_users_roles_users foreign key (user_id) references users (id) on delete cascade on update no action
);

create table if not exists task_images
(
    task_id bigint       not null,
    image   varchar(255) not null,
    constraint fk_tasks_images_tasks foreign key (task_id) references tasks (id) on delete cascade on update no action
);



CREATE TABLE "black_lists"
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "master_id"     BIGINT                                  NOT NULL,
    "cleints_phone" VARCHAR(255)                            NOT NULL
);
ALTER TABLE
    "black_lists"
    ADD PRIMARY KEY ("id");
CREATE TABLE "clients"
(
    "id"             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mobile_number"  VARCHAR(255)                            NOT NULL,
    "password"       VARCHAR(255)                            NOT NULL,
    "firstname"      VARCHAR(255)                            NOT NULL,
    "middlename"     VARCHAR(255)                            NULL,
    "secondname"     VARCHAR(255)                            NOT NULL,
    "remember_token" VARCHAR(255)                            NULL,
    "telegram_token" VARCHAR(255)                            NULL,
    "created_at"     TIMESTAMP(0) WITHOUT TIME ZONE          NOT NULL
);
ALTER TABLE
    "clients"
    ADD PRIMARY KEY ("id");
CREATE TABLE "orders"
(
    "id"             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cliend_id"      BIGINT                                  NOT NULL,
    "master_id"      BIGINT                                  NOT NULL,
    "price"          DECIMAL(8, 2)                           NOT NULL,
    "time_of_create" TIMESTAMP(0) WITHOUT TIME ZONE          NOT NULL,
    "time_of_start"  TIMESTAMP(0) WITHOUT TIME ZONE          NOT NULL,
    "time_of_end"    TIMESTAMP(0) WITHOUT TIME ZONE          NOT NULL,
    "rating"         INTEGER                                 NULL
);
ALTER TABLE
    "orders"
    ADD PRIMARY KEY ("id");
CREATE TABLE "masters"
(
    "id"             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mobile_number"  VARCHAR(255)                            NOT NULL,
    "email"          VARCHAR(255)                            NULL,
    "password"       VARCHAR(255)                            NOT NULL,
    "firstname"      VARCHAR(255)                            NOT NULL,
    "middlename"     VARCHAR(255)                            NULL,
    "secondname"     VARCHAR(255)                            NOT NULL,
    "remember_token" VARCHAR(255)                            NULL,
    "telegram_token" VARCHAR(255)                            NULL,
    "created_at"     TIMESTAMP(0) WITHOUT TIME ZONE          NOT NULL
);
ALTER TABLE
    "masters"
    ADD PRIMARY KEY ("id");
CREATE TABLE "sale_cards"
(
    "id"        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "master_id" BIGINT                                  NOT NULL,
    "name"      VARCHAR(255)                            NULL,
    "percent"   DECIMAL(8, 2)                           NOT NULL
);
ALTER TABLE
    "sale_cards"
    ADD PRIMARY KEY ("id");
CREATE TABLE "clients_sale_cards"
(
    "client_id"    BIGINT NOT NULL,
    "sale_card_id" BIGINT NOT NULL
);
CREATE TABLE "orders_services"
(
    "order_id"   BIGINT NOT NULL,
    "service_id" BIGINT NOT NULL
);
CREATE TABLE "landings"
(
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "master_id"   BIGINT                                  NOT NULL,
    "description" VARCHAR(255)                            NULL,
    "files"       BIGINT                                  NULL
);
ALTER TABLE
    "landings"
    ADD PRIMARY KEY ("id");
CREATE TABLE "services"
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "master_id"     BIGINT                                  NOT NULL,
    "name"          VARCHAR(255)                            NOT NULL,
    "comment"       VARCHAR(255)                            NULL,
    "price"         DECIMAL(8, 2)                           NOT NULL,
    "standart_time" TIME(0) WITHOUT TIME ZONE               NULL
);
ALTER TABLE
    "services"
    ADD PRIMARY KEY ("id");
ALTER TABLE
    "sale_cards"
    ADD CONSTRAINT "sale_cards_master_id_foreign" FOREIGN KEY ("master_id") REFERENCES "masters" ("id") ON DELETE CASCADE;
ALTER TABLE
    "black_lists"
    ADD CONSTRAINT "black_lists_master_id_foreign" FOREIGN KEY ("master_id") REFERENCES "masters" ("id") ON DELETE CASCADE;
ALTER TABLE
    "orders"
    ADD CONSTRAINT "orders_master_id_foreign" FOREIGN KEY ("master_id") REFERENCES "masters" ("id") ON DELETE CASCADE;
ALTER TABLE
    "orders_services"
    ADD CONSTRAINT "orders_services_service_id_foreign" FOREIGN KEY ("service_id") REFERENCES "services" ("id") ON DELETE CASCADE;
ALTER TABLE
    "landings"
    ADD CONSTRAINT "landings_master_id_foreign" FOREIGN KEY ("master_id") REFERENCES "masters" ("id") ON DELETE CASCADE;
ALTER TABLE
    "services"
    ADD CONSTRAINT "services_master_id_foreign" FOREIGN KEY ("master_id") REFERENCES "masters" ("id") ON DELETE CASCADE;
ALTER TABLE
    "clients_sale_cards"
    ADD CONSTRAINT "clients_sale_cards_sale_card_id_foreign" FOREIGN KEY ("sale_card_id") REFERENCES "sale_cards" ("id") ON DELETE CASCADE;
ALTER TABLE
    "orders_services"
    ADD CONSTRAINT "orders_services_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE;
ALTER TABLE
    "orders"
    ADD CONSTRAINT "orders_client_id_foreign" FOREIGN KEY ("cliend_id") REFERENCES "clients" ("id") ON DELETE CASCADE;
ALTER TABLE
    "clients_sale_cards"
    ADD CONSTRAINT "clients_sale_cards_client_id_foreign" FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON DELETE CASCADE;